### ISSUE TITLE
Not enough florp

### ISSUE THREAD

**Issue by TrolledWoods** [togglebyte/tinybit#1]
This is supposed to be the florp-engine but looking through the code there is not much florping going on.

Is this intentional, or is the title simply incorrect?

I think that injecting some florping into the code could solve this, for example; too manycomments, impl blocks in different files than the types, macros that are pointless and only add complexity, e.t.c.

Example of code with florp in it:
```rust
fn florp() {
     panic!("florp");
}
```

**Comment by togglebyte** [comment]
No longer the florp engine

**Comment by Parelite** [comment]
> No longer the florp engine

I can't believe that this is no longer a florp engine. How can the engine possibly function without being a florp engine.

**Comment by Bruceboy** [comment]
> No longer the florp engine

feelsbadman
