### ISSUE TITLE
Post your screenshots

### ISSUE THREAD

**Issue by dumblob** [togglebyte/tinybit#8]
I thought this repo might deserve some screenshots. If they're not in readme, let's post them here!

P.S. Even screenshots from just example or throw-away apps count!

**Comment by togglebyte** [comment]
![screenshot](https://user-images.githubusercontent.com/74262215/125284921-546cbf80-e31a-11eb-9e36-c007d0d99ec0.png)

**Comment by togglebyte** [comment]
Good idea, added here and to the README
